# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|

  config.vm.box = "ubuntu/trusty64"

  config.vm.synced_folder "./share", "/home/vagrant/share"

  config.vm.provider "virtualbox" do |vb|
    vb.gui = false
    vb.memory = "2048"
    vb.cpus = 2
  end

  # config.vm.provision "docker"

  config.vm.network :forwarded_port, guest: 18080, host: 8080

  config.vm.network :forwarded_port, guest: 13000, host: 3000 # rails

  config.vm.provision :shell, path: "bootstrap.sh", :privileged => false

  # config.vm.provision :shell, path: "install-ruby-essentials.sh", :privileged => false

  # config.vm.provision :shell, :path => "install-rvm.sh", :args => "stable", :privileged => false
  # config.vm.provision :shell, :path => "install-ruby.sh", :args => "2.2.1 rails haml", :privileged => false
end
