# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.box = "ubuntu/trusty64"

  config.vm.provision :shell, :path => "install-rvm.sh", :args => "stable", :privileged => false
  config.vm.provision :shell, :path => "install-ruby.sh", :args => "2.2.1 rails haml", :privileged => false

  config.vm.synced_folder "shared/", "/home/vagrant/shared"

end