# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|

  config.vm.box = "ubuntu/trusty64"

  config.vm.provider "virtualbox" do |vb|
    vb.gui = false
    vb.memory = "2048"
    vb.cpus = 2
  end

  config.vm.provision :shell, :path => "../common/install-essentials.sh", :privileged => false
  config.vm.provision :shell, :path => "../common/install-docker.sh", :privileged => false
end
