# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

CONFIG = {
  :URL => "https://download.elastic.co/elasticsearch/elasticsearch/elasticsearch-1.5.2.tar.gz",
  :VM_IP => "192.168.33.10"
}

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.box = "ubuntu/trusty64"

  config.vm.network "private_network", ip: "#{CONFIG[:VM_IP]}"

  config.vm.provision :shell, :path => "vm_install.sh", :args => "#{CONFIG[:URL]}", :privileged => false
end