# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

CUSTOM_CONFIG = {
	:CASSANDRA_DOWNLOAD_URL => "http://apache.osuosl.org/cassandra/2.1.2/apache-cassandra-2.1.2-bin.tar.gz" ,
	:BRIDGED_NETWORK_INTERFACE => "eth0",
	:IP_PREFIX => "192.168.50"
}

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
	(1..3).each do |i|
		config.vm.define "clusterN#{i}" do |machine|
			machine.vm.box = "ubuntu/trusty64"
			machine.vm.network "public_network", bridge: CUSTOM_CONFIG[:BRIDGED_NETWORK_INTERFACE], ip: "#{CUSTOM_CONFIG[:IP_PREFIX]}#{i}"

			machine.vm.provision :shell do |s|
				s.path = "install_cassandra.sh"
				s.args = "#{CUSTOM_CONFIG[:CASSANDRA_DOWNLOAD_URL]} clusterN#{i}"
			end
		end
	end
end