# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|

  config.vm.box = "ubuntu/trusty64"

  config.vm.synced_folder "~/work", "/home/vagrant/share"

  config.vm.provider "virtualbox" do |vb|
    vb.gui = false
    vb.memory = "2048"
    vb.cpus = 2
  end

  # run `vagrant reload` to refresh port forwarding
  config.vm.network :forwarded_port, guest: 8080, host: 18080
  config.vm.network :forwarded_port, guest: 3000, host: 13000 # rails
  config.vm.network :forwarded_port, guest: 5432, host: 15432 # postgresql

  config.vm.provision :shell, :path => "../common/install-essentials.sh", :privileged => false
  config.vm.provision :shell, :path => "../common/install-docker.sh", :privileged => false
  config.vm.provision :shell, :path => "../common/install-rvm.sh", :args => "stable", :privileged => false

  config.vm.provision :shell, :path => "bootstrap.sh", :args => "stable", :privileged => false
end
